export const fighters = [
  {
    id: 1,
    name: 'Marcus "The Hammer" Johnson',
    age: 28,
    gender: 'Male',
    photo: 'https://images.unsplash.com/photo-1727990617119-5a6a93e4c909?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxib3hpbmclMjBmaWdodGVyJTIwdHJhaW5pbmd8ZW58MXx8fHwxNzYxMjI5NDM4fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    disciplines: ['Boxing', 'MMA'],
    experience: 'Pro',
    amateurRecord: { wins: 12, losses: 3, draws: 1 },
    proRecord: { wins: 5, losses: 2, draws: 0 },
    height: '6\'1"',
    reach: '74"',
    weightClass: 'Middleweight',
    gym: 'Iron Fist Gym',
    distance: 3,
    bio: 'Looking for serious sparring partners. Focus on technical boxing and ground game.',
  },
  {
    id: 2,
    name: 'Sarah Chen',
    age: 25,
    gender: 'Female',
    photo: 'https://images.unsplash.com/photo-1734188668236-39e7e46e4390?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtbWElMjBmaWdodGVyJTIwd29ya291dHxlbnwxfHx8fDE3NjEyMjk0Mzl8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    disciplines: ['MMA', 'BJJ', 'Muay Thai'],
    experience: 'Amateur',
    amateurRecord: { wins: 8, losses: 1, draws: 0 },
    proRecord: { wins: 0, losses: 0, draws: 0 },
    height: '5\'6"',
    reach: '66"',
    weightClass: 'Bantamweight',
    gym: 'Elite Combat Academy',
    distance: 5,
    bio: 'Training for my first pro fight. Looking for technical sparring in striking and grappling.',
  },
  {
    id: 3,
    name: 'Kai "The Dragon" Rodriguez',
    age: 30,
    gender: 'Male',
    photo: 'https://images.unsplash.com/photo-1671856129089-18737be2cd6c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtdWF5JTIwdGhhaSUyMGF0aGxldGV8ZW58MXx8fHwxNzYxMjI5NDM5fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    disciplines: ['Muay Thai', 'Kickboxing'],
    experience: 'Pro',
    amateurRecord: { wins: 15, losses: 2, draws: 0 },
    proRecord: { wins: 8, losses: 3, draws: 1 },
    height: '5\'10"',
    reach: '72"',
    weightClass: 'Welterweight',
    gym: 'Thai Warriors',
    distance: 7,
    bio: 'Muay Thai specialist. Clean sparring, respect first. Available most evenings.',
  },
  {
    id: 4,
    name: 'Alex Thompson',
    age: 26,
    gender: 'Male',
    photo: 'https://images.unsplash.com/photo-1734668486909-4637ecd66408?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiamolMjB0cmFpbmluZyUyMGd5bXxlbnwxfHx8fDE3NjEyMjk0Mzl8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    disciplines: ['BJJ', 'Wrestling'],
    experience: 'Amateur',
    amateurRecord: { wins: 6, losses: 4, draws: 1 },
    proRecord: { wins: 0, losses: 0, draws: 0 },
    height: '5\'11"',
    reach: '73"',
    weightClass: 'Lightweight',
    gym: 'Grappler\'s Paradise',
    distance: 2,
    bio: 'Blue belt in BJJ, former collegiate wrestler. Looking to roll and improve.',
  },
];

export const matches = [
  {
    id: 1,
    fighter: fighters[0],
    lastMessage: 'Sounds good, see you Tuesday!',
    timestamp: '2h ago',
    unread: 2,
  },
  {
    id: 2,
    fighter: fighters[1],
    lastMessage: 'What time works for you?',
    timestamp: '1d ago',
    unread: 0,
  },
  {
    id: 3,
    fighter: fighters[2],
    lastMessage: 'Looking forward to it 🥊',
    timestamp: '3d ago',
    unread: 1,
  },
];

export const chatMessages = {
  1: [
    { id: 1, senderId: 1, text: 'Hey! Want to spar this week?', timestamp: '10:30 AM' },
    { id: 2, senderId: 'me', text: 'Yeah, I\'m free Tuesday evening', timestamp: '10:45 AM' },
    { id: 3, senderId: 1, text: 'Perfect! Iron Fist at 6pm?', timestamp: '10:47 AM' },
    { id: 4, senderId: 'me', text: 'Sounds good, see you Tuesday!', timestamp: '10:50 AM' },
  ],
  2: [
    { id: 1, senderId: 2, text: 'Hi! Down for some technical sparring?', timestamp: 'Yesterday' },
    { id: 2, senderId: 'me', text: 'Definitely! What time works for you?', timestamp: 'Yesterday' },
  ],
  3: [
    { id: 1, senderId: 'me', text: 'Want to get some rounds in?', timestamp: 'Mon' },
    { id: 2, senderId: 3, text: 'Looking forward to it 🥊', timestamp: 'Mon' },
  ],
};

export const gyms = [
  {
    id: 1,
    name: 'Iron Fist Gym',
    address: '123 Fight St, Downtown',
    distance: 2.3,
    verified: true,
    rating: 4.8,
    photo: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400',
  },
  {
    id: 2,
    name: 'Elite Combat Academy',
    address: '456 Warrior Ave, Midtown',
    distance: 4.1,
    verified: true,
    rating: 4.9,
    photo: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=400',
  },
  {
    id: 3,
    name: 'Thai Warriors',
    address: '789 Kickbox Blvd, Uptown',
    distance: 6.5,
    verified: true,
    rating: 4.7,
    photo: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
  },
];
