openapi: 3.1.0
info:
  title: Rumbler API
  version: 0.1.1
servers:
  - url: https://api.rumbler.dev
paths:
  /auth/register:
    post:
      summary: Register user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string, format: email }
                password: { type: string }
      responses:
        '201': { description: Registered }
  /auth/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string, format: email }
                password: { type: string }
      responses:
        '200': { description: OK }
components:
  schemas:
    DeckFighter:
      type: object
      properties:
        fighterId: { type: string }
        name: { type: string }
        age: { type: integer }
        gender: { type: string }
        disciplines:
          type: array
          items: { type: string }
        weightClass: { type: string }
        experience: { type: string }
        record:
          type: object
          properties:
            amateur: { type: string }
            professional:
              type: string
              nullable: true
        distanceKm: { type: number }
        avatarUrl:
          type: string
          format: uri
  /me/profile:
    get:
      summary: Get my profile
      responses: { '200': { description: OK } }
    put:
      summary: Update my profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                weight_class: { type: string }
                disciplines: { type: array, items: { type: string } }
                stance: { type: string }
                height_cm: { type: integer, minimum: 0 }
                reach_cm: { type: integer, minimum: 0 }
                experience_level:
                  type: string
                  enum: [amateur, pro]
                dob:
                  type: string
                  format: date
                gender:
                  type: string
                  enum: [male, female, nonbinary, prefer_not_to_say]
                amateur_wins:   { type: integer, minimum: 0 }
                amateur_losses: { type: integer, minimum: 0 }
                amateur_draws:  { type: integer, minimum: 0 }
                pro_wins:       { type: integer, minimum: 0 }
                pro_losses:     { type: integer, minimum: 0 }
                pro_draws:      { type: integer, minimum: 0 }
              required: [ weight_class, disciplines, experience_level ]
      responses:
        '200': { description: Updated }
  /deck:
    get:
      summary: Fetch swipe deck
      parameters:
        - in: query
          name: distance
          schema: { type: number, minimum: 1, maximum: 100 }
        - in: query
          name: discipline
          schema: { type: string }
        - in: query
          name: experience
          schema:
            type: string
            enum: [beginner, intermediate, advanced, pro]
        - in: query
          name: gender
          schema:
            type: string
            enum: [male, female, non-binary]
      responses:
        '200':
          description: Fighters available for swipe actions
          content:
            application/json:
              schema:
                type: object
                properties:
                  query:
                    type: object
                    additionalProperties: true
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/DeckFighter'
  /deck/{fighterId}/like:
    post:
      summary: Like a fighter (optimistic match check)
      parameters:
        - in: path
          name: fighterId
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Like accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  liked: { type: boolean }
                  match:
                    type: object
                    nullable: true
                    properties:
                      fighterId: { type: string }
                      createdAt: { type: string, format: date-time }
  /deck/{fighterId}/pass:
    post:
      summary: Pass on a fighter
      parameters:
        - in: path
          name: fighterId
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Pass acknowledged
          content:
            application/json:
              schema:
                type: object
                properties:
                  passed: { type: boolean }
  /matches:
    get:
      summary: List my matches
      responses:
        '200':
          description: Current mutual likes
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        fighterId: { type: string }
                        lastMessage: { type: string }
                        matchedAt: { type: string, format: date-time }
  /matches/{id}/messages:
    get:
      summary: List messages
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses: { '200': { description: OK } }
    post:
      summary: Send message
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body: { type: string }
                media_key: { type: string }
      responses: { '201': { description: Created } }
  /gyms:
    get:
      summary: List verified gyms
      responses: { '200': { description: OK } }
  /bookings:
    post:
      summary: Create booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                match_id: { type: string }
                gym_id: { type: string }
                start_time: { type: string, format: date-time }
                ruleset: { type: string }
      responses:
        '201': { description: Created }
  /bookings/{id}/checkin:
    post:
      summary: Check-in to gym
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lat: { type: number }
                lon: { type: number }
      responses:
        '200': { description: OK }
